module.exports.main = {
    botToken: "",
    locationSets: {
        standard: [
            "Aeroplane",
            "Army Base",
            "Art Museum",
            "Bank",
            "Beach",
            "Casino",
            "Cat Show",
            "Cathedral",
            "Cemetery",
            "Circus Tent",
            "Coal Mine",
            "Construction Site",
            "Consulate",
            "Corporate Party",
            "Crusader Army",
            "Film Studio",
            "Gaming Convention",
            "Harbour Docks",
            "Hospital",
            "Hotel",
            "Ice Hockey Stadium",
            "Jazz Club",
            "Library",
            "Night Bar",
            "Ocean Liner",
            "Passenger Train",
            "Petrol Station",
            "Pirate Ship",
            "Polar Station",
            "Police Station",
            "Race Track",
            "Restaurant",
            "Retirement Home",
            "Rock Concert",
            "School",
            "Space Station",
            "Stadium",
            "Submarine",
            "Supermarket",
            "The U.N.",
            "Theme Park",
            "Trailerpark",
            "University",
            "Vineyard",
            "Wedding",
            "Zoo"
        ],
        gameOfThrones: [
            "Braavos",
            "Casterly Rock",
            "Castle Black",
            "Dragonstone",
            "High Garden",
            "Iron Islands",
            "Kings Landing",
            "Meereen",
            "Moat Cailin",
            "Oldtown",
            "Pentos",
            "Riverrun",
            "Storms End",
            "Sunspear",
            "The Dreadfort",
            "The Eyrie",
            "The Twins",
            "Volantis",
            "Winterfell"
        ],
        harryPotter: [
            "Azkaban",
            "Beauxbatons",
            "Durmstrang",
            "Gringotts Wizarding Bank",
            "Hogsmeade Station",
            "Hogwarts",
            "Honeydukes",
            "Little Whinging",
            "Malfoy Manor",
            "Ministry of Magic",
            "Ollivanders",
            "Platform Nine and Three-Quaters",
            "Spinners End",
            "The Burrow",
            "The Leaky Cauldron"
        ]
    }
};
